### ISSUE TITLE
display() - support aggregate value filtering (nice to have)

### ISSUE THREAD

**Issue by ptitzler** [ibm-watson-data-lab/pixiedust#127]
As a user, I want to apply a filter that eliminates data points from the display. Map example: display only regions where the average lot size is 10,000sf+. Today I can only do that by shaping the data (aggregate and apply filter) before I launch the visualization. It would be nice if I could define a filter while I explore the visualization.

**Comment by vabarbosa** [comment]
duplicated by #288 
resolved in PR #578
