### ISSUE TITLE
display() histogram: rename BIN SIZE label

### ISSUE THREAD

**Issue by ptitzler** [ibm-watson-data-lab/pixiedust#185]
To `Number of bins` to reduce ambiguity. `Bin size` could mean several things, such as number of bins or the range of values in a bin, which are fundamentally different.

**Comment by DTAIEB** [comment]
@ptitzler bin size is a very common term for histogram. The range of values is cut into intervals (bin) and this means the size of one of these bin/interval. It doesn't mean the number of bins, which depends on the range itself. The histogram then shows frequency of the values that fall within each interval.

**Comment by cdarendt** [comment]
@DTAIEB
Your description is NOT how "Bin Size" is used in display().
In display(), adjusting the "Bin Size" changes the NUMBER of bins in the histogram.

Please re-open this item and update the display() source code (pixiedust/display/chart/renderers/commonOptions.py) to change the "Bin Size" label to "Number of Bins" or "Bin Count":
Current code:
        'name': 'binsize',
        'description': 'Bin size',

Correct code:
        'name': 'binsize',
        'description': 'Bin Count',

**Comment by DTAIEB** [comment]
Ok, even though bin size and bin count are tightly correlated, I can see how the current label is not reflecting its true meaning. Re-opening this item for 1.0.11

**Comment by vabarbosa** [comment]
PR #442
