### ISSUE TITLE
mapbox

### ISSUE THREAD

**Issue by MargrietGroenendijk** [ibm-watson-data-lab/pixiedust#194]
I am getting a `list out of range` error when trying to make a map of the average house price per state with mapbox. 

Same for average population by country.

![image](https://cloud.githubusercontent.com/assets/17784157/23470705/0414fd40-fe9f-11e6-8714-95c36ae6e8f2.png)

**Comment by rajrsingh** [comment]
@MargrietGroenendijk I can't reproduce. Can you send me your notebook? (the .ipynb file)

**Comment by rajrsingh** [comment]
Key can't be any field other than latitude and longitude. We should restrict key field entry to only those values that make sense

**Comment by rajrsingh** [comment]
acceptable values for Key input:
- must be 2 fields
- one must be called 'lat','latitude', or 'y'
- one must be called 'lon','longitude', or 'x'
