### ISSUE TITLE
display() table view: Display more than 100 rows

### ISSUE THREAD

**Issue by benhuds** [ibm-watson-data-lab/pixiedust#270]
PixieDust currently displays only the first 100 rows of a dataset, and there is no functionality to view the rest of the data in the table viewer (next 100 rows/previous 100 rows).

**Comment by seansabour** [comment]
I also think this would be a nice feature to include if you could maybe have a dropdown that would allow you to see (10,20,100,500) number of rows per page.

**Comment by benhuds** [comment]
@seansabour True. However, I did realize that the original intention of the table view was purely to _preview_ the data before you create a visualization (which I did not catch at first hand).

**Comment by seansabour** [comment]
Ah @benhuds, i didn't know that.

**Comment by rajrsingh** [comment]
fixed by #595
