### ISSUE TITLE
display() table view: Search bar only works on first 100 rows of data

### ISSUE THREAD

**Issue by benhuds** [ibm-watson-data-lab/pixiedust#271]
(Follow-up to #270) Search functionality only returns results from the first 100 rows of data shown in the initial table view.

E.g.
1. Row 150 of my dataset has "name" value = "Bob"
2. I want to search for all rows containing "Bob" so I type "Bob" in the search bar
3. Row 150 will not be returned in the result

**Comment by DTAIEB** [comment]
Needs design discussion to be able scope the work

**Comment by rajrsingh** [comment]
fixed by #595 since table can now use the dataset filter
