### ISSUE TITLE
display() table view: datetime64 values in Pandas appear as Unix timestamps

### ISSUE THREAD

**Issue by benhuds** [ibm-watson-data-lab/pixiedust#279]
`datetime64` values turn into their corresponding Unix timestamps when converting a Pandas dataframe to a Spark dataframe, so for example, `2014-01-02` shows up as `1388620800000000000` (dtype: long) in PixieDust.  I also checked the Spark dataframe before using `display()` and the `datetime64` values have been converted to `bigint` values.

How the date values look in Pandas:

<img width="152" alt="screen shot 2017-03-27 at 4 59 22 pm" src="https://cloud.githubusercontent.com/assets/3121544/24377888/f5de7524-130e-11e7-8dfc-d485e8003045.png">

After converting to Spark dataframe:

<img width="549" alt="screen shot 2017-03-27 at 4 59 42 pm" src="https://cloud.githubusercontent.com/assets/3121544/24377867/dfb9898c-130e-11e7-90b6-ec7aa475ba3a.png">

Code to reproduce:

```python
import pandas as pd
import pandas.io.data as web
import datetime

start = datetime.date(2014,1,1)
end = datetime.date.today()

ibm = web.DataReader('IBM','yahoo',start,end)
apple = web.DataReader('AAPL', 'yahoo', start, end)
microsoft = web.DataReader('MSFT','yahoo',start,end)

stocks = pd.DataFrame({"IBM": ibm['Adj Close'],\
                      "AAPL": apple['Adj Close'],\
                      "MSFT": microsoft['Adj Close']})

# Reset index so we can use date as key in Line Chart visualization 
stocks.reset_index(inplace=True)

import pixiedust

sqlContext = SQLContext(sc)
st = sqlContext.createDataFrame(stocks)
display(st)
```

**Comment by DTAIEB** [comment]
#278
