### ISSUE TITLE
As a Developer, I want to be able to share bokeh rendered graphs on DSX

### ISSUE THREAD

**Issue by seansabour** [ibm-watson-data-lab/pixiedust#280]
### Expected behavior
To be able to view the graphs rendered by Bokeh when sharing a notebook on DSX.

### Actual behavior
Graph does not appear, 
<img width="1792" alt="screen shot 2017-03-27 at 4 24 51 pm" src="https://cloud.githubusercontent.com/assets/9244813/24382615/2489870e-130c-11e7-8c78-8d3ed9374406.png">

### Steps to reproduce the behavior
Create a simple bokeh rendered graph and share the notebook.

**Comment by DTAIEB** [comment]
This problem has been fixed a while ago
