### ISSUE TITLE
As a user, I want to be able to filter for desired values and visualize that data

### ISSUE THREAD

**Issue by benhuds** [ibm-watson-data-lab/pixiedust#288]
Comments from @DTAIEB:

> I think it would be really beneficial to the user if we were to add a “filter” functionality, where the user can specify fine grain queries e.g. age > 21, description contains XXXX, etc… This filter needs to run against the whole datasets, not only the 100 sample rows, which means it will take more time to complete

> I see the filter as a not associated only to the preview pane, but rather to all the visualizations. e.g. the user specifies the filter and then can visualize the results with the pane preview, the charts, etc..

> Finally, similar to charts that hides matplotlib and spark complexity, the filter is a nice way to hide Spark complexity for filtering information

> **important to let user zoom in on the data that’s interesting to them**

The last thought is a good summary of what I think a user would expect from a filter.

### Appearance and Functionality

I imagine the filter could appear within the `display()` API.  There is also the question of whether the filter would coexist with the search bar.

Right now, I can think of a couple of ways a user could use the filter within the `display()` API:

1. Excel-style: a user would type a filter into the search bar (more typing)
2. Looker-style: a user would click on a field to add to a list of filters (and then specify the filter) and continually add desired filters (more clicking)

The latter would depend upon the datatype of the field and have some predefined operations: e.g. if it is an int then you could filter "equal to" or "greater than," etc. and if it is a string then you could filter "contains" or "matches."

Applying the filter would result in the classic preview table as if you entered `display(filteredData)` in the cell.  Then you could proceed to visualize as usual or continue to mess around with the filters (with the option to reset to original data without filters).

**Comment by vabarbosa** [comment]
duplicate #127 
resolved in PR #578
