### ISSUE TITLE
As a data scientist, I want to blog a Tutorial to show that Pixiedust works swith Scala

### ISSUE THREAD

**Issue by rajrsingh** [ibm-watson-data-lab/pixiedust#32]

**Comment by rajrsingh** [comment]
Follow up on this tutorial: https://medium.com/@DustinVanStee/how-to-add-a-custom-library-to-a-jupyter-scala-notebook-in-ibm-data-science-experience-dsx-d85e97bc2e10#.ag5gg8hua

**Comment by mmcelaney** [comment]
Refer to this Scala stuff: https://ibm-cds-labs.github.io/pixiedust/scalabridge.html
