### ISSUE TITLE
I want to be able to visualize streaming data, e.g. from the Streaming Analytics service

### ISSUE THREAD

**Issue by natashadsilva** [ibm-watson-data-lab/pixiedust#321]
### Expected behavior
I have an incoming stream of data, such as a stream of patient vital signs as described in this [notebook](https://apsportal.ibm.com/exchange/public/entry/view/9fc33ce7301f10e21a9f92039cad29a6) .

I'd like to use PixieDust to display this data such that the graph is continuously updated :  ![image](https://developer.ibm.com/streamsdev/wp-content/uploads/sites/15/2017/04/dsx-1.gif)

### Actual behavior
I don't see how this is possible using PixieDust at the moment, it seems to only support displaying a static Spark or Pandas DataFrames.

**Comment by DTAIEB** [comment]
@natashadsilva do you know who we can easily simulate this streaming data? this would be helpful to build the corresponding pixiedust plugin

**Comment by natashadsilva** [comment]
@DTAIEB I created this DSX notebook for that purpose. 
https://github.com/natashadsilva/samples/blob/master/Visualize%20data%20from%20Streams%20in%20PixieDust.ipynb
It demonstrates my use case. 
You just need to create an instance of the streaming analytics service on Bluemix, and run the cells.

**Comment by natashadsilva** [comment]
@DTAIEB any outlook or comments for this feature?

**Comment by DTAIEB** [comment]
@natashadsilva hasn't made it to the top of the pile yet mostly due to resources, but it's getting there. Rough outlook would be mid July

**Comment by jinxuan** [comment]
So will it run on spark structure streaming right? Is mid-July scheduled as an expected time to release this version?

**Comment by DTAIEB** [comment]
@jinxuan This item is covering low level interfaces, defining how PixieDust will interact with Streaming data. The first commit (targeted at PixieDust 1.0.11) will include a few implementations: Kafka, IBM Streams and regular rest end point. Spark structure streaming will come later, however, you should be able to create your own PixieDust Streaming Adapter right away.
