### ISSUE TITLE
Brunel as a Render Engine

### ISSUE THREAD

**Issue by GraemeHutcheon** [ibm-watson-data-lab/pixiedust#326]
Are there any plans to utilize Brunel as a Render engine in PixieDust ?

**Comment by DTAIEB** [comment]
@GraemeHutcheon This has come up but no firm plan yet due to lack of resources.

**Comment by DTAIEB** [comment]
Brunel renderer implementation is ready to be included in PixieDust 1.1.3.
Brunel provides feature-rich interactive data visualizations, see: http://brunel.mybluemix.net/docs/ for more details.
The Brunel renderer for Pixiedust support all charts types: bar, line, scatter, pie, histogram and maps.
For Maps, we added extra options for heatmap, treemap and chords
