### ISSUE TITLE
As a notebook developer, I want to `use display() to display graphframe as star graph` so that `it is easier visualize components

### ISSUE THREAD

**Issue by charles2588** [ibm-watson-data-lab/pixiedust#354]
As a notebook developer, I want to `use display() to display graphframe as star graph` so that `it is easier visualize components` 
Python 2.7/3.5 both doesn't work with spark 2.0 

### Expected behavior
display() to display graphframe in nodelinkgraph type graph so that .

![image](https://user-images.githubusercontent.com/5734421/26851995-8667ef0a-4ac1-11e7-8683-c00a262e86ed.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/5734421/26851906-35ee13e2-4ac1-11e7-8934-14b195c51f74.png)

### Steps to reproduce the behavior
v = sqlContext.createDataFrame([
    ("a", "Alice", 34),
    ("b", "Bob", 36),
    ("c", "Charlie", 30),
    ("d", "David", 29),
    ("e", "Esther", 32),
    ("f", "Fanny", 36)
], ["id", "name", "age"])
# Edge DataFrame
e = sqlContext.createDataFrame([
    ("a", "b", "friend"),
    ("b", "c", "follow"),
    ("c", "b", "follow"),
    ("f", "c", "follow"),
    ("e", "f", "follow"),
    ("e", "d", "friend"),
    ("d", "a", "friend")
], ["src", "dst", "relationship"])
# Create a GraphFrame
g4 = GraphFrame(v, e)

![image](https://user-images.githubusercontent.com/5734421/26851941-5d3e4b4c-4ac1-11e7-823f-6c0ac4647ed9.png)

**Comment by vabarbosa** [comment]
addressed in pr #370 which will be included in v1.0.7
