### ISSUE TITLE
As a UI developer, I want more flexibility in the display of a table

### ISSUE THREAD

**Issue by jacquesroy** [ibm-watson-data-lab/pixiedust#380]
It is currently possible to remove the headers for "schema" and "table" but it is not possible to remove the search input. Additional flexibility should be provided
It should be possible to:
- Remove "schema" independently of "table" and vice versa
- Rename "table" to a more appropriate name
- Format the table output. For example "10.2264" could become "$10.23"

I understand that some of this could be an issue of documentation

**Comment by rajrsingh** [comment]
fixed in #595
