### ISSUE TITLE
Update PixieApp documentation

### ISSUE THREAD

**Issue by DTAIEB** [ibm-watson-data-lab/pixiedust#398]
As a `Developer`, I want to `use and up to date PixieApp documentation` so that `I can create PixieApps`

### Expected behavior
Up to Date PixieApp documentation

### Actual behavior
PixieApp documentation is missing the latest additions

### Steps to reproduce the behavior
https://ibm-watson-data-lab.github.io/pixiedust/pixieapps.html

**Comment by mikebroberg** [comment]
PR is in for 1.0.8 docs: https://github.com/ibm-watson-data-lab/pixiedust/pull/411
