### ISSUE TITLE
As a user, I want to use the sampleData API to load JSON data

### ISSUE THREAD

**Issue by jordangeorge** [ibm-watson-data-lab/pixiedust#408]
The `pixiedust.sampleData()` allows for loading CSV data from a url. However, it does not support JSON data. Updating the API to support JSON can make it easier to load data from other sources (e.g., bCharts)

**Comment by vabarbosa** [comment]
the `sampleData` API has been updated to allow loading of JSON data.

**_pixiedust_.sampleData(_dataframe_, _type='json'_)**

where available options for `type` includes `json` or `csv` and defaults to `csv` when not included.

example,

```
import pixiedust

df = pixiedust.sampleData('https://raw.githubusercontent.com/ibm-watson-data-lab/open-data/master/cities/cities.json', type='json')

display(df)
```
