### ISSUE TITLE
Maps: aggregation should be disabled in chart options

### ISSUE THREAD

**Issue by mikebroberg** [ibm-watson-data-lab/pixiedust#410]
As a PixieDust user, I don't want my map visualization to try to aggregate lat/lon values so that my visualizations load with less work

### Expected behavior
I don't need to run an aggregation on map lat/lon values.

### Actual behavior
PixieDust makes me choose an aggregation

### Steps to reproduce the behavior
Use a Mapbox render in PixieDust.

Looking at the code with David, and there's a `showAggregation` method you just have to set to false for the map option, and it won't load that drop down menu and force the visualization anymore.

**Comment by rajrsingh** [comment]
@mikebroberg @DTAIEB I don't see this problem anymore. Is it fixed?

**Comment by rajrsingh** [comment]
ready to close this?
