### ISSUE TITLE
As user I want to use Python 3.5 to do "jupyter pixiedust install"

### ISSUE THREAD

**Issue by romulogoncalves** [ibm-watson-data-lab/pixiedust#437]
### Expected behavior
jupyter pixiedust install
Step 1: PIXIEDUST_HOME: /root/pixiedust
        Keep y/n [y]? n
Please enter a PIXIEDUST_HOME location: /data/local/pixiedust
Step 2: SPARK_HOME: /data/local/pixiedust/bin/spark
        Keep y/n [y]? n
Step 2: Please enter a SPARK_HOME location: /usr/lib/spark
downloaded spark cloudant jar: /data/local/pixiedust/bin/cloudant-spark-v2.0.0-185.jar
Step 3: SCALA_HOME: /data/local/pixiedust/bin/scala
        Keep y/n [y]? n
Step 3: Please enter a SCALA_HOME location: /usr/share/scala
String is Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL

Step 4: Kernel Name: Python with Pixiedust (Spark 2.1)
        Keep y/n [y]? n
Please enter a Kernel Name: Python with Pixiedust (Spark 2.1)
self.kernelInternalName pythonwithpixiedustspark21
[PixiedustInstall] Installed kernelspec pythonwithpixiedustspark21 in /root/.local/share/jupyter/kernels/pythonwithpixiedustspark21
Downloading intro notebooks into /data/local/pixiedust/notebooks
...https://github.com/ibm-watson-data-lab/pixiedust/raw/master/notebook/PixieDust 1 - Easy Visualizations.ipynb : done
...https://github.com/ibm-watson-data-lab/pixiedust/raw/master/notebook/PixieDust 2 - Working with External Data.ipynb : done
...https://github.com/ibm-watson-data-lab/pixiedust/raw/master/notebook/PixieDust 3 - Scala and Python.ipynb : done
...https://github.com/ibm-watson-data-lab/pixiedust/raw/master/notebook/PixieDust 4 - Add External Spark Packages.ipynb : done
...https://github.com/ibm-watson-data-lab/pixiedust/raw/master/notebook/PixieDust 5 - Stash to Cloudant.ipynb : done
...https://github.com/ibm-watson-data-lab/pixiedust/raw/master/notebook/PixieDust Contribute.ipynb : done

/####################################################################################################
/#       Congratulations: Kernel Python with Pixiedust (Spark 2.1) was successfully created in /root/.local/share/jupyter/kernels/pythonwithpixiedustspark21
/#       You can start the Notebook server with the following command:
/#               jupyter notebook /data/local/pixiedust/notebooks
/####################################################################################################

### Actual behavior
jupyter pixiedust install
Step 1: PIXIEDUST_HOME: /root/pixiedust
        Keep y/n [y]? n
Please enter a PIXIEDUST_HOME location: /data/local/pixiedust
Step 2: SPARK_HOME: /data/local/pixiedust/bin/spark
        Keep y/n [y]? n
Step 2: Please enter a SPARK_HOME location: /usr/lib/spark-2.1.1-bin-without-hadoop
downloaded spark cloudant jar: /data/local/pixiedust/bin/cloudant-spark-v2.0.0-185.jar
Step 3: SCALA_HOME: /data/local/pixiedust/bin/scala
        Keep y/n [y]? n
Step 3: Please enter a SCALA_HOME location: /usr/lib/scala
Directory /usr/lib/scala does not exist
        Create y/n [y]? n
Step 3: SCALA_HOME: /data/local/pixiedust/bin/scala
        Keep y/n [y]? n
Step 3: Please enter a SCALA_HOME location: /usr/share/scala
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-pixiedust", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/install/pixiedustapp.py", line 42, in main
    PixiedustJupyterApp.launch_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-2>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 296, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python3.5/dist-packages/install/createKernel.py", line 248, in parse_command_line
    installed_scala_version = self.get_scala_version()
  File "/usr/local/lib/python3.5/dist-packages/install/createKernel.py", line 429, in get_scala_version
    return get_scala_version_from_dir(self.scala_home)
NameError: name 'get_scala_version_from_dir' is not defined
### Steps to reproduce the behavior
jupyter pixiedust install
Step 1: PIXIEDUST_HOME: /root/pixiedust
        Keep y/n [y]? n
Please enter a PIXIEDUST_HOME location: /data/local/pixiedust
Step 2: SPARK_HOME: /data/local/pixiedust/bin/spark
        Keep y/n [y]? n
Step 2: Please enter a SPARK_HOME location: /usr/lib/spark-2.1.1-bin-without-hadoop
downloaded spark cloudant jar: /data/local/pixiedust/bin/cloudant-spark-v2.0.0-185.jar
Step 3: SCALA_HOME: /data/local/pixiedust/bin/scala
        Keep y/n [y]? n
Step 3: Please enter a SCALA_HOME location: /usr/lib/scala
Directory /usr/lib/scala does not exist
        Create y/n [y]? n
Step 3: SCALA_HOME: /data/local/pixiedust/bin/scala
        Keep y/n [y]? n
Step 3: Please enter a SCALA_HOME location: /usr/share/scala

**Reason:**
https://github.com/ibm-watson-data-lab/pixiedust/blob/master/install/createKernel.py#L428
*Instead of:*
def get_scala_version(self):
  return get_scala_version_from_dir(self.scala_home)

*Should not it be:*
def get_scala_version(self):
  return self.get_scala_version_from_dir(self.scala_home)

**Comment by DTAIEB** [comment]
@markwatsonatx can you take a look?
