### ISSUE TITLE
Publish PixieApps as a web application

### ISSUE THREAD

**Issue by DTAIEB** [ibm-watson-data-lab/pixiedust#450]
As a user, I want to be able to publish PixieApps as web apps so that Line of Business users can use it as a regular web app without being forced to log in a Notebook

**User Story:**
1. Data Scientist use Notebook to load, enrich, analyze data and create analytics (machine learning models, etc...)
2. From same notebook, Developer create a PixieApp to operationalize these analytics
3. Once ready, Developer publishes the PixieApp as a web application

**Terminology:**
PixieGateway: Web application server able to load and run PixieApps.

**Implementation:**
1. PixieGateway is built on top of the [Jupyter Kernel Gateway](https://github.com/jupyter/kernel_gateway) using a custom personality.
Command to launch the PixieGateway: **jupyter pixiegateway <options>**

![image](https://user-images.githubusercontent.com/4912140/30832106-e5fe5eec-a217-11e7-8c3a-5b9df8945f1c.png)

2. From Notebook, user will be able to publish the PixieApp using a toolbar button
![image](https://user-images.githubusercontent.com/4912140/30832386-ee6bacbe-a218-11e7-87cc-20bc4bef99f7.png)
The Publish configuration dialog will contain the following 3 panels:
a. Basic configuration:'
![image](https://user-images.githubusercontent.com/4912140/30832502-45b3e89c-a219-11e7-9334-9ec25f75d22d.png)
b. List of package dependencies (automatically detected by static code analysis). User will be able to manually adjust.
![image](https://user-images.githubusercontent.com/4912140/30832551-6e1d8838-a219-11e7-82c0-05152cead812.png)
c. Kernel Spec Information
![image](https://user-images.githubusercontent.com/4912140/30832568-8222c046-a219-11e7-9abd-048d393978d9.png)
d. User can use the Publish button, to deploy the Notebook and its PixieApp. If successful a url link to the PixieApp will be provided:
![image](https://user-images.githubusercontent.com/4912140/30832630-c5818c32-a219-11e7-8777-2cf9cb8f5e15.png)

3. Running the PixieApp:
-On start, the PixieGateway will read all the published notebooks and perform static analysis on the python code to detect which cell the PixieApp is located. Only one PixieApp per Notebook will be allowed (all existing cells below the PixieApp will be ignored).
-Every cell above the PixieApp will be considered warmup code and run only once. The PixieApp code (run code) will be run on client requests.
-PixieGateway will manage and load balance multiple clients (max number configurable) based on users load.
-Multiple PixieApps may be run within the same kernel, but users have to option to force a particular PixieApp to run in a dedicated kernel. To avoid variable name conflict, the warmup and run code will be rewritten to namespace the name of the variables.
-There will be an admin console to manage all the deployed apps:
![image](https://user-images.githubusercontent.com/4912140/30832787-74c1eb2e-a21a-11e7-863b-062a14421fa4.png)

**Comment by DTAIEB** [comment]
cc /@parente

**Comment by parente** [comment]
@DTAIEB looks like what we discussed.  Would you like me to @ mention some folks on this issue who have an interest in Jupyter dashboards so they can chime in?

**Comment by DTAIEB** [comment]
@parente yes please, can't remember who was interested in this topic. First pass implementation is in david-gateway-branch, but there is much more to be spec'ed out:
-Security
-Scalability
-Compatibility with existing dashboard server
-....

**Comment by parente** [comment]
> -Compatibility with existing dashboard server

FYI, the dashboard server wound up in jupyter-attic/dashboards_server as planned.

**Comment by parente** [comment]
cc'ing @ddavidebor @cbcunc @jhelie @rserbitar as users who have repeatedly expressed interest in dashboarding and related activities in Jupyter in the past. Sorry for the spam if your interests have changed.

**Comment by ddavidebor** [comment]
Still extremely interested in dashboarding

**Comment by xmnlab** [comment]
I am interesting too ...

Actually I want to replace my widget chart by pixiedust (
https://github.com/OpenDataScienceLab/skdata ... This still out of date ..
I need to do a PR from my fork) but I need a way to generate charts like
weka, comparing all the fields.

Is it possible?

I am very busy now ... But in 2 weeks I should have more time to help.

**Comment by DTAIEB** [comment]
@xmnlab PixieDust comes will a set of built-in visualizations but also provides extensibility apis to write your [own](https://ibm-watson-data-lab.github.io/pixiedust/writeviz.html)
As far as publishing to a web app, only [pixieapp](https://ibm-watson-data-lab.github.io/pixiedust/pixieapps.html) are supported at the moment. Wrapping a chart into a pixieapp is very easy however.

**Comment by xmnlab** [comment]
Thanks @DTAIEB I will take a look :+1:

**Comment by DTAIEB** [comment]
Alpha with PixieDust 1.1 has been released on Pypi. See blog post here: https://medium.com/ibm-watson-data-lab/deploy-your-analytics-as-web-apps-using-pixiedusts-1-1-release-d08067584a14
cc/ @parente @xmnlab @ddavidebor

**Comment by xmnlab** [comment]
Thanks @DTAIEB I will take a look :+1:
