### ISSUE TITLE
As someone trying to see data on a map, I'd like to see Mapbox maps by default

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/pixiedust#451]
### Expected behavior
When a user toggles to a map view, we should load by default the Mapbox map, with the API key provided by Mapbox.

### Actual behavior
Today, we load Google maps, but we don't have an API key for that. So, the first impression seems broken.

**Comment by ptitzler** [comment]
It would be desirable to "hide" the default key from the UI. A user can override the key (if desired) by entering a custom value (like it is done today).
