### ISSUE TITLE
Map display: MapBox renderer not available until after trying to render a Google map

### ISSUE THREAD

**Issue by ulemanstreaming** [ibm-watson-data-lab/pixiedust#458]
### Expected behavior
In the display frame, click Chart > Map. In the Options dialog, I can select the map renderer. Because MapBox is the one most often used and Google is relatively rare, MapBox is the default anyway.
Alternatively, I can set the default map renderer in a keyword argument to display().

### Actual behavior
On first use, the Options dialog asks for a Google API key and gives no option to choose MapBox. The only way to get out of this is to set whatever options will let you click OK, let the display viewer come up with a failure, and then use the renderer selection box to pick MapBox. Then you get to set the options you really want, including MapBox Access Token, in the Options dialog.

### Steps to reproduce the behavior
In a fresh notebook (once you've displayed any MapBox  map in a notebook, that'll be the default for any other map), try to use the map visualization in display() on any data that contains coordinates.

**Comment by rajrsingh** [comment]
duplicates #451 which was fixed
