### ISSUE TITLE
Releases are not tagged

### ISSUE THREAD

**Issue by rolweber** [ibm-watson-data-lab/pixiedust#468]
There have been at least a dozen releases of pixiedust on PyPI (up to 1.0.11 and now 1.1.0), but there's only one tag here on GitHub. This makes it awfully hard for any observer to track which changes have gone into which release. Or even to find out which releases there are, because PyPI hides all but the latest.
https://pypi.python.org/pypi/pixiedust
https://github.com/ibm-watson-data-lab/pixiedust/releases

Would it be possible to create tags for the code levels you're releasing to PyPI?
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by DTAIEB** [comment]
Agreed, we'll start tagging each PyPi release from now on.
A release was created for 1.1
