### ISSUE TITLE
Add info about loading data from your local computer

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/pixiedust#485]
Right now we only show in our docs on loading data how to load from URL, but often people will have CSVs on their computers.

See here:
https://ibm-watson-data-lab.github.io/pixiedust/loaddata.html

Here's an example:
pixiedust.sampleData('file:///Users/bradfordnoble/pixiedust/data/nz.csv')

**Comment by mikebroberg** [comment]
OK addressed in #543

**Comment by mikebroberg** [comment]
Actually in #544 . Sorry about that.
