### ISSUE TITLE
PixieDust should be able to display() JSON directly

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/pixiedust#489]
Today, if I want to display() a Python "JSON" object, I need to manually install pandas and then pass the JSON object to a pandas dataframe.

Interestingly, I do not need to take these steps to display() JSON in pixiedust_node. (The pandas stuff is done automatically in pixiedust_node.)

**Comment by DTAIEB** [comment]
Implemented a fix. Now PixieDust will natively render dictionaries or array of dictionaries without the need to turn them into Pandas dataframes first
