### ISSUE TITLE
Doc updates for 1.1.2

### ISSUE THREAD

**Issue by DTAIEB** [ibm-watson-data-lab/pixiedust#495]
- PixieApp documentation updates [David, in Box]
- Pixiegateway new section: [from blog, intro]
   - Install [from blog 1]
   - Chart Sharing [from blog 2]
   - PixieApp publishing [from blog 1]
   - Admin [David, new]
Add to README for PixieGateway: https://github.com/ibm-watson-data-lab/pixiegateway [Mike]

**Comment by mikebroberg** [comment]
README addressed in https://github.com/ibm-watson-data-lab/pixiegateway/pull/4
