### ISSUE TITLE
Dependency on kernel gateway doesn't make sense on DSX

### ISSUE THREAD

**Issue by rolweber** [ibm-watson-data-lab/pixiedust#498]
Pixiedust 1.1 added a dependency on Jupyter kernel gateway, to support the new pixiedust gateway feature. On a hosted service like DSX, this feature will not work. However, the dependency on the kernel gateway can lead to up- and downgrades of other Jupyter and IPython components, which interferes with the regular operation of notebook kernels. One concern in particular is that the changed versions may be missing fixes that were implemented for DSX.

**Comment by DTAIEB** [comment]
New repo for pixiegateway has been created https://github.com/ibm-watson-data-lab/pixiegateway. Refactoring is in progress
