### ISSUE TITLE
As a user I want to use PIXIEAPP to publish app, but not successful due to python statement using % instead of format

### ISSUE THREAD

**Issue by maychu** [ibm-watson-data-lab/pixiedust#510]
I had this statement in my python:
  repourlall='https://github.ibm.com/api/v3/repos/%s/issues?state=all' % current_repourl

When changed above to:
  repourlall='https://github.ibm.com/api/v3/repos/{}/issues?state=all'.format(current_repourl) 
 - then the IMPORT list is correct .  And the publish works

### Expected behavior
Expect the PUBLISH to be able to handle the python code I have

### Actual behavior
This resulted in a PUBLISH error:
![pixiedusterr](https://user-images.githubusercontent.com/13426072/33493942-884ebf92-d676-11e7-82cb-c957913d32fc.jpg)

### Steps to reproduce the behavior
1) Have the above python statement in you notebook: which results in this error when publishing.
NOTE: My notebook is complicated (will share with David directly), but will see if I can strip it down and share in this defect

**Comment by maychu** [comment]
Info from chat with David:
Ah yes PixieDust is doing static analysis of the code to resolve magics who are not proper python syntax. This is definitely a bug I will look at. In the meantime don't use % to concat the strings use .format instead

**Comment by DTAIEB** [comment]
A fix has been provided in PR #542
