### ISSUE TITLE
As a user, I want to publish my pixieapp with v1.1.4 (david's current version), using python3.5, and I get an error when the chart/table is rendering

### ISSUE THREAD

**Issue by maychu** [ibm-watson-data-lab/pixiedust#518]
### Expected behavior
1) I upgraded to pixiedust 1.14
!pip install -e git+https://github.com/ibm-watson-data-lab/pixiedust@david-gateway-branch#egg=pixiedust

2) I changed my current notebook to use PYTHON 3.5
- then I removed the UNICODE conversion code (which had caused me problems).
 - which is removing the call to remove conversions (pixieapp publish did not like the python2 syntax)

3) when running the pixieapp
- when click SUBMIT button (for graph/table), I get an error
>>  When using PYTHON2 .  When click submit button, the graph/table shows up properly

### Actual behavior
PIXIEAPP gets error

\nTemplateAssertionErrorTraceback (most recent call last)\n<ipython-input-19-548f42c54b66> in <module>()
----> 1 display(GitApp_instance,runInDialog='false',nostore_pixieapp='GitApp_instance',nostore_ispix='true',handlerId='__main___GitApp_id',cell_id='4FA2C5FE917B47D58115A5984400954A',nostore_pixiedust='true',nostore_cw='1460',org_params='nostore_pixieapp,nostore_pixiedust,runInDialog,nostore_ispix,handlerId',nostore_bokeh='false',chartContents='true',nostore_figureOnly='true')
\n/gpfs/global_fs01/sym_shared/YS1Prod/user/sbf4-61114dedf7ac86-46d6240294e8/notebook/work/src/pixiedust/pixiedust/display/__init__.py in display(entity, **kwargs)
    138                 return
    139 
--> 140             displayHandler.render()
    141         finally:
    142             if pr is not None:
\n/gpfs/global_fs01/sym_shared/YS1Prod/user/sbf4-61114dedf7ac86-46d6240294e8/notebook/work/src/pixiedust/pixiedust/display/display.py in render(self)
    289         else:
    290             start = time.clock()
--> 291             self.doRender(handlerId)
    292             self.executionTime = time.clock() - start
    293 
\n/gpfs/global_fs01/sym_shared/YS1Prod/user/sbf4-61114dedf7ac86-46d6240294e8/notebook/work/src/pixiedust/pixiedust/display/app/pixieapp.py in doRender(self, handlerId)
    136                     retValue = retValue.ret_value
    137                 if isinstance(retValue, string_types):
--> 138                     self._addHTMLTemplateString(retValue, **injectedArgs )
    139                 elif isinstance(retValue, dict):
    140                     body = self.renderTemplateString(retValue.get("body", ""))
\n/gpfs/global_fs01/sym_shared/YS1Prod/user/sbf4-61114dedf7ac86-46d6240294e8/notebook/work/src/pixiedust/pixiedust/display/display.py in _addHTMLTemplateString(self, source, **kwargs)
    311     def _addHTMLTemplateString(self, source, **kwargs):
    312         self._addHTML(
--> 313             self.renderTemplateString(source, **kwargs)
    314         )
    315 
\n/gpfs/global_fs01/sym_shared/YS1Prod/user/sbf4-61114dedf7ac86-46d6240294e8/notebook/work/src/pixiedust/pixiedust/display/display.py in renderTemplateString(self, source, **kwargs)
    307 
    308     def renderTemplateString(self, source, **kwargs):
--> 309         return self.env.from_string(source).render(self._getTemplateArgs(**kwargs))
    310 
    311     def _addHTMLTemplateString(self, source, **kwargs):
\n/gpfs/global_fs01/sym_shared/YS1Prod/user/sbf4-61114dedf7ac86-46d6240294e8/notebook/work/src/pixiedust/pixiedust/utils/template.py in from_string(self, source, **kwargs)
    100 
    101     def from_string(self, source, **kwargs):
--> 102         return self.env.from_string(source, globals=kwargs)
    103 
    104     def getTemplate(self, name):
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/environment.py in from_string(self, source, globals, template_class)
    860         globals = self.make_globals(globals)
    861         cls = template_class or self.template_class
--> 862         return cls.from_code(self, self.compile(source), globals, None)
    863 
    864     def make_globals(self, d):
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/environment.py in compile(self, source, name, filename, raw, defer_init)
    563         except TemplateSyntaxError:
    564             exc_info = sys.exc_info()
--> 565         self.handle_exception(exc_info, source_hint=source_hint)
    566 
    567     def compile_expression(self, source, undefined_to_none=True):
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/environment.py in handle_exception(self, exc_info, rendered, source_hint)
    752             self.exception_handler(traceback)
    753         exc_type, exc_value, tb = traceback.standard_exc_info
--> 754         reraise(exc_type, exc_value, tb)
    755 
    756     def join_path(self, template, parent):
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/_compat.py in reraise(tp, value, tb)
     35     def reraise(tp, value, tb=None):
     36         if value.__traceback__ is not tb:
---> 37             raise value.with_traceback(tb)
     38         raise value
     39 
\n<unknown> in template()
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/environment.py in _generate(self, source, name, filename, defer_init)
    513         .. versionadded:: 2.5
    514         """
--> 515         return generate(source, self, name, filename, defer_init=defer_init)
    516 
    517     def _compile(self, source, filename):
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/compiler.py in generate(node, environment, name, filename, stream, defer_init)
     60     generator = environment.code_generator_class(environment, name, filename,
     61                                                  stream, defer_init)
---> 62     generator.visit(node)
     63     if stream is None:
     64         return generator.stream.getvalue()
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/visitor.py in visit(self, node, *args, **kwargs)
     36         f = self.get_visitor(node)
     37         if f is not None:
---> 38             return f(node, *args, **kwargs)
     39         return self.generic_visit(node, *args, **kwargs)
     40 
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/compiler.py in visit_Template(self, node, frame)
    814         self.pull_locals(frame)
    815         self.pull_dependencies(node.body)
--> 816         self.blockvisit(node.body, frame)
    817         self.outdent()
    818 
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/compiler.py in blockvisit(self, nodes, frame)
    490         try:
    491             for node in nodes:
--> 492                 self.visit(node, frame)
    493         except CompilerExit:
    494             pass
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/visitor.py in visit(self, node, *args, **kwargs)
     36         f = self.get_visitor(node)
     37         if f is not None:
---> 38             return f(node, *args, **kwargs)
     39         return self.generic_visit(node, *args, **kwargs)
     40 
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/compiler.py in visit_Output(self, node, frame)
   1351                         self.write('environment, ')
   1352                     close += 1
-> 1353                 self.visit(argument, frame)
   1354                 self.write(')' * close + ', ')
   1355             self.outdent()
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/visitor.py in visit(self, node, *args, **kwargs)
     36         f = self.get_visitor(node)
     37         if f is not None:
---> 38             return f(node, *args, **kwargs)
     39         return self.generic_visit(node, *args, **kwargs)
     40 
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/compiler.py in visit_Filter(self, node, frame)
   1563         func = self.environment.filters.get(node.name)
   1564         if func is None:
-> 1565             self.fail('no filter named %r' % node.name, node.lineno)
   1566         if getattr(func, 'contextfilter', False):
   1567             self.write('context, ')
\n/usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages/jinja2/compiler.py in fail(self, msg, lineno)
    425     def fail(self, msg, lineno):
    426         """Fail with a :exc:`TemplateAssertionError`."""
--> 427         raise TemplateAssertionError(msg, lineno, self.name, self.filename)
    428 
    429     def temporary_identifier(self):
\nTemplateAssertionError: no filter named 'tojson'\n

![err](https://user-images.githubusercontent.com/13426072/33682115-585d2810-da7b-11e7-981b-b3343c9175f0.jpg)
![err2](https://user-images.githubusercontent.com/13426072/33682199-a063d276-da7b-11e7-865d-4c46e5e97d56.jpg)
![err3](https://user-images.githubusercontent.com/13426072/33682205-a2ecb7d8-da7b-11e7-8251-45baec1afbd1.jpg)

### Steps to reproduce the behavior
1) upload my notebook "pixieapp-github-dev-final" (contact me if you need, but David has a copy)
2) change notebook to be using Python 3.5 and spark 2
3) run notebook, and see the pixieapp - click SUBMIT

**Comment by DTAIEB** [comment]
@maychu which version of jinja2 are you using? You can find out the version using the following command from your notebook:
```

**Comment by maychu** [comment]
!pip show jinja2

​

---
Metadata-Version: 1.1
Name: Jinja2
Version: 2.8
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /usr/local/src/conda3_runtime.v29/4.1.1/lib/python3.5/site-packages
Requires: MarkupSafe
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Web Environment
  Intended Audience :: Developers
  License :: OSI Approved :: BSD License
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Topic :: Internet :: WWW/HTTP :: Dynamic Content
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Text Processing :: Markup :: HTML
Entry-points:
  [babel.extractors]
  jinja2 = jinja2.ext:babel_extract[i18n]

**Comment by DTAIEB** [comment]
@maychu this is the issue, you need to upgrade jinja2. 

Please run this command and try again:
!pip install -U jinja2

**Comment by maychu** [comment]
Is there a anywhere that documents what level we need components to be at ?
