### ISSUE TITLE
As a user, when I use my PIXIEAPP: I want to use the Brunnel chart's functionality - filter, but it is not working properly

### ISSUE THREAD

**Issue by maychu** [ibm-watson-data-lab/pixiedust#522]
1) JUST PIXIEDUST
When I use display(), for my rendered brunnel bar chart, it works fine. The filtering capabilities work

2) PIXIEAPP, which has a brunnel chart
When I have a PIXIEAPP - which has a brunnel bar chart.  The FILTER DROP DOWN SHOWN does not function properly.

### Expected behavior
The filter should only show the data, I have chosen

### Actual behavior
The filter does nothing, and I get the same CHART as I had before I made options available.

**Comment by DTAIEB** [comment]
Fix provided in PR #524
