### ISSUE TITLE
Display > table: number of rows doesn't honor max rows constraint

### ISSUE THREAD

**Issue by ptitzler** [ibm-watson-data-lab/pixiedust#601]
PD 1.1.7

* load a data set with a couple of hundred rows
* `display(df)`
* choose table chart; note the number of rows displayed
* restrict the "#number of rows to display" to some other value
* observe how the "Showing X of Y" count changes to "random" values 

Examples: 
* set max to 500: displays 528 of 528
* set max to 200: displays 113 of 113
* ...

**Comment by rajrsingh** [comment]
I noticed this earlier also and forgot to create an issue :(

**Comment by rajrsingh** [comment]
@ptitzler @DTAIEB @vabarbosa I think I've identified the problem. In `pandasDataFrameHandler.py` there's this:
> workingDF = workingDF.sample(frac=(float(maxRows) / float(count)),replace=False)

So we're sampling a percentage of the dataframe. Instead shouldn't we be doing this?
> workingDF = workingDF.sample(n=int(maxRows),replace=False)

reference: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sample.html
