### ISSUE TITLE
Renderer MapBox raises "a bytes-like object is required, not 'str'" error in Python 3.x 

### ISSUE THREAD

**Issue by Tomas-Kadlec-01** [ibm-watson-data-lab/pixiedust#602]
PixieDust 1.17: Using a Python 3.x kernel in local Jupyter notebook, the pixiedust google maps renderer fails with a bytes-like object is required, not 'str'. The problemn is not observed if Python 2.x is used, unfortunately Gateway Docker image doesn't work for Python 2.x

Very standard use of display with lat,long for keys and couple of numeric values

http://159.122.179.202:32224/pixieapp/ProdPixieApp
(section maps -> Mapbox map is not displayed)

**Comment by DTAIEB** [comment]
@Tomas-Kadlec-01 Yes, this regression slipped by us in 1.1.7. I have a fix that I'll commit in master and will make a new PixieDust release on PyPi tomorrow. 
cc/ @glynnbird
