### ISSUE TITLE
How to connect cloudant  ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [ibm-watson-data-lab/pixiedust#663]
When I am trying to run code:  

```
import pixiedust
pixiedust.installPackage("com.typesafe.play:play-json_2.11:2.5.9")
pixiedust.installPackage("org.apache.bahir:spark-sql-cloudant_2.11:0")
```

facing following error.

![image](https://user-images.githubusercontent.com/11150958/37747526-79305ef8-2da1-11e8-8dcc-2b9aacffe5b9.png)

**Comment by DTAIEB** [comment]
@ZaheerUdDeen If you recently upgraded PixieDust version, make sure to restart the kernel and refresh the page. If that doesn't solve the issue, please issue the following command in a new cell:
```
%pixiedustLog -l debug
```
then paste the output in this issue.

**Comment by ZaheerUdDeen** [comment]
This issue has been solved.
