### ISSUE TITLE
jupyter pixiedust install -- unattended installation

### ISSUE THREAD

**Issue by elgalu** [ibm-watson-data-lab/pixiedust#669]
Currently `jupyter pixiedust install` requires user intervention responding yes/no and filling in some values.

How can I perform a fully unattended installation? i.e. via a Dockerfile.

**Comment by DTAIEB** [comment]
@elgalu There already an option to run the install silently using --silent. You can combine it with --spark<version> e.g. --spark2.2 to specify a particular version of Spark.

**Comment by DTAIEB** [comment]
Closing the issue since solution already exists. Feel free to reopen if needed.
